shell bash --login -c "/home/yoyomu/.local/bin/anifetch -W 60 -H 35 example.mp4 -ff -c '--symbols wide --fg-only' || true; exec bash"
confirm_os_window_close 0
shell_integration enabled
font_size 10
cursor_trail 1
selection_background #dddddd
cursor_shape beam
focus_follows_mouse yes
allow_remote_control yes
underline_hyperlinks hover
mouse_map left triplepress ungrabbed mouse_selection line

# BEGIN_KITTY_FONTS
font_family      family='Roboto Mono' postscript_name=RobotoMono-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

selection_foreground #3e3e3e
selection_background #c1ddff
foreground #DDDAD3
background #242423
color0     #252525
color8     #555555
color1     #be7472
color9     #ff9900
color2     #5A6F5E
color10    #97bb98
color3     #989772
color11    #fefdbc
color4     #7199bc
color12    #9fbdde
color5     #727399
color13    #989abc
color6     #719899
color14    #6fbbbc
color7     #7f7f7f
color15    #feffff
