shell bash --login -c "/home/yoyomu/.local/bin/anifetch -W 60 -H 35 example.mp4 -ff -c '--symbols wide --fg-only' || true; exec bash"
confirm_os_window_close 0
shell_integration enabled
font_size 10
cursor_trail 1
selection_background #dddddd
cursor_shape beam
focus_follows_mouse yes
allow_remote_control yes
underline_hyperlinks hover
mouse_map left triplepress ungrabbed mouse_selection line
linux_display_server wayland
enable_audio_bell no
sync_to_monitor no
dynamic_background_opacity yes

# BEGIN_KITTY_FONTS
font_family      family='Roboto Mono' postscript_name=RobotoMono-Regular
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

foreground           #D2D2CD
background           #242A25
selection_foreground #D2D2CD
selection_background #6C8D73
color0   #596259
color8   #6B7F7B
color1   #6B5150
color9   #EE9157
color2   #5C7768
color10  #6C8D73
color3   #D2B543
color11  #D2D2CD
color4   #77ABBF
color12  #7EADBF
color5   #6B5150
color13  #EE9157
color6   #6B7F7B
color14  #77ABBF
color7   #D2D2CD
color15  #FFFFFF
