listener {
    timeout = 250
    on-timeout = brightnessctl set 15%
    on-resume = brightnessctl set 100%
}

listener {
    timeout = 325
    on-timeout = pkill waybar; brightnessctl set 1%
    on-resume = brightnessctl set 100%; waybar &
}   

listener {
    timeout = 350                               
    on-timeout = hyprctl dispatch dpms off                      
    on-resume = hyprctl dispatch dpms on && brightnessctl -r          
}

listener {
    timeout = 415
    on-timeout = systemctl poweroff
}

