monitorv2 {
  output = desc:Chimei Innolux Corporation 0x152B
  mode = 1920x1080@60
  position = 1440x92
  scale = 1.5
  bitdepth = 10
  cm = hdr
}

monitorv2 {
  output = desc:LG Electronics W1934 0x0001357E
  mode = 1440x900@70
  position = 0x0
  scale = 1
  bitdepth = 10
  cm = hdr
}

